[workspace]
resolver = "2"
members = [
    "platform/platform-cli",
    "platform/host",
    "platform/guest",
    "platform/guest-sdk",
    "platform/guest-sdk-macros",
    "platform/registry_server",
    "platform/signaling_server",
    "platform/studio",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
lto = true
strip = true
panic = "abort"
