[package]
name = "host"
version.workspace = true
edition.workspace = true
default-run = "main"

[dependencies]
anyhow = "1"
bevy = { version = "0.14", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_asset",
    "bevy_scene",
    "bevy_ui",
    "bevy_text",
    "multi_threaded",
    "default_font",
] }
gltf = "1.4"
serde_json = "1"
signaling_server = { path = "../signaling_server" }
tungstenite = "0.26"
wasmtime = "35"
